server:
  port: 10087
  servlet:
    context-path: /driver

# log\u65E5\u5FD7\u914D\u7F6E\u6587\u4EF6\u8DEF\u5F84
logging:
  config: classpath:log4j2-system-config.yml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/system_driver?
    username: lele
    password: lele
