package com.leleplus.dao;

import com.leleplus.bean.ActionRecord;
import com.leleplus.bean.ActionRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    long countByExample(ActionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int deleteByExample(ActionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int insert(ActionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int insertSelective(ActionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    List<ActionRecord> selectByExample(ActionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    ActionRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") ActionRecord record, @Param("example") ActionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByExample(@Param("record") ActionRecord record, @Param("example") ActionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByPrimaryKeySelective(ActionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByPrimaryKey(ActionRecord record);
}