package com.leleplus.dao;

import com.leleplus.bean.CarInfo;
import com.leleplus.bean.CarInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    long countByExample(CarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int deleteByExample(CarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int insert(CarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int insertSelective(CarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    List<CarInfo> selectByExample(CarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    CarInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") CarInfo record, @Param("example") CarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int updateByExample(@Param("record") CarInfo record, @Param("example") CarInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int updateByPrimaryKeySelective(CarInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    int updateByPrimaryKey(CarInfo record);
}