package com.leleplus.dao;

import com.leleplus.bean.Practice;
import com.leleplus.bean.PracticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PracticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    long countByExample(PracticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByExample(PracticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insert(Practice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insertSelective(Practice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    List<Practice> selectByExample(PracticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    Practice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Practice record, @Param("example") PracticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExample(@Param("record") Practice record, @Param("example") PracticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKeySelective(Practice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKey(Practice record);
}