package com.leleplus.dao;

import com.leleplus.bean.StudentArchives;
import com.leleplus.bean.StudentArchivesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentArchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    long countByExample(StudentArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int deleteByExample(StudentArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int insert(StudentArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int insertSelective(StudentArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    List<StudentArchives> selectByExample(StudentArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    StudentArchives selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentArchives record, @Param("example") StudentArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByExample(@Param("record") StudentArchives record, @Param("example") StudentArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByPrimaryKeySelective(StudentArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    int updateByPrimaryKey(StudentArchives record);
}