package com.leleplus.bean;

import java.io.Serializable;

public class Administrator implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.realname
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.gender
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.address
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.wage
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Double wage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.job
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_administrator.user_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_administrator
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.id
     *
     * @return the value of driver_administrator.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.id
     *
     * @param id the value for driver_administrator.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.realname
     *
     * @return the value of driver_administrator.realname
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.realname
     *
     * @param realname the value for driver_administrator.realname
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.gender
     *
     * @return the value of driver_administrator.gender
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.gender
     *
     * @param gender the value for driver_administrator.gender
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.address
     *
     * @return the value of driver_administrator.address
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.address
     *
     * @param address the value for driver_administrator.address
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.wage
     *
     * @return the value of driver_administrator.wage
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Double getWage() {
        return wage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.wage
     *
     * @param wage the value for driver_administrator.wage
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setWage(Double wage) {
        this.wage = wage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.job
     *
     * @return the value of driver_administrator.job
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.job
     *
     * @param job the value for driver_administrator.job
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_administrator.user_id
     *
     * @return the value of driver_administrator.user_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_administrator.user_id
     *
     * @param userId the value for driver_administrator.user_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", realname=").append(realname);
        sb.append(", gender=").append(gender);
        sb.append(", address=").append(address);
        sb.append(", wage=").append(wage);
        sb.append(", job=").append(job);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}