package com.leleplus.bean;

import java.io.Serializable;

public class CoachArchives implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.user_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.realname
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.birthday
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.age
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.gender
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.id_photo
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String idPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.user_face
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String userFace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.national
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String national;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.address
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.wage
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Double wage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.driver_type
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String driverType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.car_info_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long carInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.create_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.is_enable
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_coach_archives.status
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.id
     *
     * @return the value of driver_coach_archives.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.id
     *
     * @param id the value for driver_coach_archives.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.user_id
     *
     * @return the value of driver_coach_archives.user_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.user_id
     *
     * @param userId the value for driver_coach_archives.user_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.realname
     *
     * @return the value of driver_coach_archives.realname
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.realname
     *
     * @param realname the value for driver_coach_archives.realname
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.birthday
     *
     * @return the value of driver_coach_archives.birthday
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.birthday
     *
     * @param birthday the value for driver_coach_archives.birthday
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.age
     *
     * @return the value of driver_coach_archives.age
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.age
     *
     * @param age the value for driver_coach_archives.age
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.gender
     *
     * @return the value of driver_coach_archives.gender
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.gender
     *
     * @param gender the value for driver_coach_archives.gender
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.id_photo
     *
     * @return the value of driver_coach_archives.id_photo
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getIdPhoto() {
        return idPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.id_photo
     *
     * @param idPhoto the value for driver_coach_archives.id_photo
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setIdPhoto(String idPhoto) {
        this.idPhoto = idPhoto == null ? null : idPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.user_face
     *
     * @return the value of driver_coach_archives.user_face
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getUserFace() {
        return userFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.user_face
     *
     * @param userFace the value for driver_coach_archives.user_face
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setUserFace(String userFace) {
        this.userFace = userFace == null ? null : userFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.national
     *
     * @return the value of driver_coach_archives.national
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getNational() {
        return national;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.national
     *
     * @param national the value for driver_coach_archives.national
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setNational(String national) {
        this.national = national == null ? null : national.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.address
     *
     * @return the value of driver_coach_archives.address
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.address
     *
     * @param address the value for driver_coach_archives.address
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.wage
     *
     * @return the value of driver_coach_archives.wage
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Double getWage() {
        return wage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.wage
     *
     * @param wage the value for driver_coach_archives.wage
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setWage(Double wage) {
        this.wage = wage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.driver_type
     *
     * @return the value of driver_coach_archives.driver_type
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getDriverType() {
        return driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.driver_type
     *
     * @param driverType the value for driver_coach_archives.driver_type
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setDriverType(String driverType) {
        this.driverType = driverType == null ? null : driverType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.car_info_id
     *
     * @return the value of driver_coach_archives.car_info_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getCarInfoId() {
        return carInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.car_info_id
     *
     * @param carInfoId the value for driver_coach_archives.car_info_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setCarInfoId(Long carInfoId) {
        this.carInfoId = carInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.create_time
     *
     * @return the value of driver_coach_archives.create_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.create_time
     *
     * @param createTime the value for driver_coach_archives.create_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.is_enable
     *
     * @return the value of driver_coach_archives.is_enable
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.is_enable
     *
     * @param isEnable the value for driver_coach_archives.is_enable
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_coach_archives.status
     *
     * @return the value of driver_coach_archives.status
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_coach_archives.status
     *
     * @param status the value for driver_coach_archives.status
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", realname=").append(realname);
        sb.append(", birthday=").append(birthday);
        sb.append(", age=").append(age);
        sb.append(", gender=").append(gender);
        sb.append(", idPhoto=").append(idPhoto);
        sb.append(", userFace=").append(userFace);
        sb.append(", national=").append(national);
        sb.append(", address=").append(address);
        sb.append(", wage=").append(wage);
        sb.append(", driverType=").append(driverType);
        sb.append(", carInfoId=").append(carInfoId);
        sb.append(", createTime=").append(createTime);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}