package com.leleplus.bean;

import java.io.Serializable;

public class Practice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_practice.id
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_practice.student_archive_id
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    private Long studentArchiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_practice.practice_time
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    private Long practiceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_practice.practice_type
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    private String practiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_practice.status
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_practice
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_practice.id
     *
     * @return the value of driver_practice.id
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_practice.id
     *
     * @param id the value for driver_practice.id
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_practice.student_archive_id
     *
     * @return the value of driver_practice.student_archive_id
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public Long getStudentArchiveId() {
        return studentArchiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_practice.student_archive_id
     *
     * @param studentArchiveId the value for driver_practice.student_archive_id
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public void setStudentArchiveId(Long studentArchiveId) {
        this.studentArchiveId = studentArchiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_practice.practice_time
     *
     * @return the value of driver_practice.practice_time
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public Long getPracticeTime() {
        return practiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_practice.practice_time
     *
     * @param practiceTime the value for driver_practice.practice_time
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public void setPracticeTime(Long practiceTime) {
        this.practiceTime = practiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_practice.practice_type
     *
     * @return the value of driver_practice.practice_type
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public String getPracticeType() {
        return practiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_practice.practice_type
     *
     * @param practiceType the value for driver_practice.practice_type
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public void setPracticeType(String practiceType) {
        this.practiceType = practiceType == null ? null : practiceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_practice.status
     *
     * @return the value of driver_practice.status
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_practice.status
     *
     * @param status the value for driver_practice.status
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_practice
     *
     * @mbg.generated Mon Jan 20 23:27:50 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentArchiveId=").append(studentArchiveId);
        sb.append(", practiceTime=").append(practiceTime);
        sb.append(", practiceType=").append(practiceType);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}