package com.leleplus.bean;

import java.io.Serializable;

public class StudentAssociateCoach implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.student_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.coach_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long coachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.create_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.expiration_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long expirationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.is_enable
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.status
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_student_associate_coach.description
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_student_associate_coach
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.id
     *
     * @return the value of driver_student_associate_coach.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.id
     *
     * @param id the value for driver_student_associate_coach.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.student_id
     *
     * @return the value of driver_student_associate_coach.student_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.student_id
     *
     * @param studentId the value for driver_student_associate_coach.student_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.coach_id
     *
     * @return the value of driver_student_associate_coach.coach_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.coach_id
     *
     * @param coachId the value for driver_student_associate_coach.coach_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setCoachId(Long coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.create_time
     *
     * @return the value of driver_student_associate_coach.create_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.create_time
     *
     * @param createTime the value for driver_student_associate_coach.create_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.expiration_time
     *
     * @return the value of driver_student_associate_coach.expiration_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.expiration_time
     *
     * @param expirationTime the value for driver_student_associate_coach.expiration_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setExpirationTime(Long expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.is_enable
     *
     * @return the value of driver_student_associate_coach.is_enable
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.is_enable
     *
     * @param isEnable the value for driver_student_associate_coach.is_enable
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.status
     *
     * @return the value of driver_student_associate_coach.status
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.status
     *
     * @param status the value for driver_student_associate_coach.status
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_student_associate_coach.description
     *
     * @return the value of driver_student_associate_coach.description
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_student_associate_coach.description
     *
     * @param description the value for driver_student_associate_coach.description
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_student_associate_coach
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", coachId=").append(coachId);
        sb.append(", createTime=").append(createTime);
        sb.append(", expirationTime=").append(expirationTime);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", status=").append(status);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}