package com.leleplus.bean;

import java.io.Serializable;

public class Subject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.student_archive_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long studentArchiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.sub_name
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String subName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.is_pass
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Integer isPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.score_a
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String scoreA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.score_b
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String scoreB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.exam_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private Long examTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.exam_room
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String examRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_subject.exam_machine_no
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private String examMachineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_subject
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.id
     *
     * @return the value of driver_subject.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.id
     *
     * @param id the value for driver_subject.id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.student_archive_id
     *
     * @return the value of driver_subject.student_archive_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getStudentArchiveId() {
        return studentArchiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.student_archive_id
     *
     * @param studentArchiveId the value for driver_subject.student_archive_id
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setStudentArchiveId(Long studentArchiveId) {
        this.studentArchiveId = studentArchiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.sub_name
     *
     * @return the value of driver_subject.sub_name
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getSubName() {
        return subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.sub_name
     *
     * @param subName the value for driver_subject.sub_name
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setSubName(String subName) {
        this.subName = subName == null ? null : subName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.is_pass
     *
     * @return the value of driver_subject.is_pass
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Integer getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.is_pass
     *
     * @param isPass the value for driver_subject.is_pass
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setIsPass(Integer isPass) {
        this.isPass = isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.score_a
     *
     * @return the value of driver_subject.score_a
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getScoreA() {
        return scoreA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.score_a
     *
     * @param scoreA the value for driver_subject.score_a
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setScoreA(String scoreA) {
        this.scoreA = scoreA == null ? null : scoreA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.score_b
     *
     * @return the value of driver_subject.score_b
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getScoreB() {
        return scoreB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.score_b
     *
     * @param scoreB the value for driver_subject.score_b
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setScoreB(String scoreB) {
        this.scoreB = scoreB == null ? null : scoreB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.exam_time
     *
     * @return the value of driver_subject.exam_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public Long getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.exam_time
     *
     * @param examTime the value for driver_subject.exam_time
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setExamTime(Long examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.exam_room
     *
     * @return the value of driver_subject.exam_room
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getExamRoom() {
        return examRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.exam_room
     *
     * @param examRoom the value for driver_subject.exam_room
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setExamRoom(String examRoom) {
        this.examRoom = examRoom == null ? null : examRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_subject.exam_machine_no
     *
     * @return the value of driver_subject.exam_machine_no
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public String getExamMachineNo() {
        return examMachineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_subject.exam_machine_no
     *
     * @param examMachineNo the value for driver_subject.exam_machine_no
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    public void setExamMachineNo(String examMachineNo) {
        this.examMachineNo = examMachineNo == null ? null : examMachineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Mon Jan 20 23:27:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentArchiveId=").append(studentArchiveId);
        sb.append(", subName=").append(subName);
        sb.append(", isPass=").append(isPass);
        sb.append(", scoreA=").append(scoreA);
        sb.append(", scoreB=").append(scoreB);
        sb.append(", examTime=").append(examTime);
        sb.append(", examRoom=").append(examRoom);
        sb.append(", examMachineNo=").append(examMachineNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}