package com.leleplus.bean;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.id
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.username
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.password
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_user
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.id
     *
     * @return the value of driver_user.id
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.id
     *
     * @param id the value for driver_user.id
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.username
     *
     * @return the value of driver_user.username
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.username
     *
     * @param username the value for driver_user.username
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.password
     *
     * @return the value of driver_user.password
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.password
     *
     * @param password the value for driver_user.password
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_user
     *
     * @mbg.generated Sat Jan 18 01:07:10 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}