package com.leleplus.bean;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.login_Id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.telphone
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.rfid_card_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String rfidCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.id_card
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.email
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.username
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.password
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.role_name
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.role_code
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_user.enable
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_user
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.id
     *
     * @return the value of driver_user.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.id
     *
     * @param id the value for driver_user.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.login_Id
     *
     * @return the value of driver_user.login_Id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.login_Id
     *
     * @param loginId the value for driver_user.login_Id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.telphone
     *
     * @return the value of driver_user.telphone
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.telphone
     *
     * @param telphone the value for driver_user.telphone
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.rfid_card_id
     *
     * @return the value of driver_user.rfid_card_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getRfidCardId() {
        return rfidCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.rfid_card_id
     *
     * @param rfidCardId the value for driver_user.rfid_card_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setRfidCardId(String rfidCardId) {
        this.rfidCardId = rfidCardId == null ? null : rfidCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.id_card
     *
     * @return the value of driver_user.id_card
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.id_card
     *
     * @param idCard the value for driver_user.id_card
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.email
     *
     * @return the value of driver_user.email
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.email
     *
     * @param email the value for driver_user.email
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.username
     *
     * @return the value of driver_user.username
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.username
     *
     * @param username the value for driver_user.username
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.password
     *
     * @return the value of driver_user.password
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.password
     *
     * @param password the value for driver_user.password
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.role_name
     *
     * @return the value of driver_user.role_name
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.role_name
     *
     * @param roleName the value for driver_user.role_name
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.role_code
     *
     * @return the value of driver_user.role_code
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.role_code
     *
     * @param roleCode the value for driver_user.role_code
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_user.enable
     *
     * @return the value of driver_user.enable
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_user.enable
     *
     * @param enable the value for driver_user.enable
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_user
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginId=").append(loginId);
        sb.append(", telphone=").append(telphone);
        sb.append(", rfidCardId=").append(rfidCardId);
        sb.append(", idCard=").append(idCard);
        sb.append(", email=").append(email);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}