package com.leleplus.dao;

import com.leleplus.bean.Administrator;
import com.leleplus.bean.AdministratorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    long countByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insertSelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    List<Administrator> selectByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    Administrator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExample(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_administrator
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKey(Administrator record);
}