package com.leleplus.dao;

import com.leleplus.bean.CoachArchives;
import com.leleplus.bean.CoachArchivesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoachArchivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    long countByExample(CoachArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByExample(CoachArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insert(CoachArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insertSelective(CoachArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    List<CoachArchives> selectByExample(CoachArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    CoachArchives selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") CoachArchives record, @Param("example") CoachArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExample(@Param("record") CoachArchives record, @Param("example") CoachArchivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKeySelective(CoachArchives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_coach_archives
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKey(CoachArchives record);
}