package com.leleplus.dao;

import com.leleplus.bean.Subject;
import com.leleplus.bean.SubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    long countByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    List<Subject> selectByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    Subject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Subject record, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByExample(@Param("record") Subject record, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    int updateByPrimaryKey(Subject record);
}