package com.leleplus.bean;

import java.io.Serializable;

public class ActionRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_action_record.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_action_record.user_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_action_record.action_time
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long actionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_action_record.action_content
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String actionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_action_record.ip_address
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_action_record.city
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_action_record
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_action_record.id
     *
     * @return the value of driver_action_record.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_action_record.id
     *
     * @param id the value for driver_action_record.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_action_record.user_id
     *
     * @return the value of driver_action_record.user_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_action_record.user_id
     *
     * @param userId the value for driver_action_record.user_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_action_record.action_time
     *
     * @return the value of driver_action_record.action_time
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getActionTime() {
        return actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_action_record.action_time
     *
     * @param actionTime the value for driver_action_record.action_time
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setActionTime(Long actionTime) {
        this.actionTime = actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_action_record.action_content
     *
     * @return the value of driver_action_record.action_content
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getActionContent() {
        return actionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_action_record.action_content
     *
     * @param actionContent the value for driver_action_record.action_content
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setActionContent(String actionContent) {
        this.actionContent = actionContent == null ? null : actionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_action_record.ip_address
     *
     * @return the value of driver_action_record.ip_address
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_action_record.ip_address
     *
     * @param ipAddress the value for driver_action_record.ip_address
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_action_record.city
     *
     * @return the value of driver_action_record.city
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_action_record.city
     *
     * @param city the value for driver_action_record.city
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_action_record
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", actionTime=").append(actionTime);
        sb.append(", actionContent=").append(actionContent);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", city=").append(city);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}