package com.leleplus.bean;

import java.io.Serializable;

public class CarInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.Car_license_number
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String carLicenseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.purchase_date
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.purchase_price
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Double purchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.vehicle_type
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String vehicleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.brand
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_car_info.coach_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private Long coachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_car_info
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.id
     *
     * @return the value of driver_car_info.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.id
     *
     * @param id the value for driver_car_info.id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.Car_license_number
     *
     * @return the value of driver_car_info.Car_license_number
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getCarLicenseNumber() {
        return carLicenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.Car_license_number
     *
     * @param carLicenseNumber the value for driver_car_info.Car_license_number
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setCarLicenseNumber(String carLicenseNumber) {
        this.carLicenseNumber = carLicenseNumber == null ? null : carLicenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.purchase_date
     *
     * @return the value of driver_car_info.purchase_date
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.purchase_date
     *
     * @param purchaseDate the value for driver_car_info.purchase_date
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setPurchaseDate(Long purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.purchase_price
     *
     * @return the value of driver_car_info.purchase_price
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Double getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.purchase_price
     *
     * @param purchasePrice the value for driver_car_info.purchase_price
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setPurchasePrice(Double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.vehicle_type
     *
     * @return the value of driver_car_info.vehicle_type
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.vehicle_type
     *
     * @param vehicleType the value for driver_car_info.vehicle_type
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType == null ? null : vehicleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.brand
     *
     * @return the value of driver_car_info.brand
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.brand
     *
     * @param brand the value for driver_car_info.brand
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_car_info.coach_id
     *
     * @return the value of driver_car_info.coach_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Long getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_car_info.coach_id
     *
     * @param coachId the value for driver_car_info.coach_id
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setCoachId(Long coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_car_info
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", carLicenseNumber=").append(carLicenseNumber);
        sb.append(", purchaseDate=").append(purchaseDate);
        sb.append(", purchasePrice=").append(purchasePrice);
        sb.append(", vehicleType=").append(vehicleType);
        sb.append(", brand=").append(brand);
        sb.append(", coachId=").append(coachId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}