package com.leleplus.bean;

import java.util.ArrayList;
import java.util.List;

public class SubjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public SubjectExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdIsNull() {
            addCriterion("student_archive_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdIsNotNull() {
            addCriterion("student_archive_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdEqualTo(Long value) {
            addCriterion("student_archive_id =", value, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdNotEqualTo(Long value) {
            addCriterion("student_archive_id <>", value, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdGreaterThan(Long value) {
            addCriterion("student_archive_id >", value, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdGreaterThanOrEqualTo(Long value) {
            addCriterion("student_archive_id >=", value, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdLessThan(Long value) {
            addCriterion("student_archive_id <", value, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdLessThanOrEqualTo(Long value) {
            addCriterion("student_archive_id <=", value, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdIn(List<Long> values) {
            addCriterion("student_archive_id in", values, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdNotIn(List<Long> values) {
            addCriterion("student_archive_id not in", values, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdBetween(Long value1, Long value2) {
            addCriterion("student_archive_id between", value1, value2, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andStudentArchiveIdNotBetween(Long value1, Long value2) {
            addCriterion("student_archive_id not between", value1, value2, "studentArchiveId");
            return (Criteria) this;
        }

        public Criteria andSubNameIsNull() {
            addCriterion("sub_name is null");
            return (Criteria) this;
        }

        public Criteria andSubNameIsNotNull() {
            addCriterion("sub_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubNameEqualTo(String value) {
            addCriterion("sub_name =", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameNotEqualTo(String value) {
            addCriterion("sub_name <>", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameGreaterThan(String value) {
            addCriterion("sub_name >", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameGreaterThanOrEqualTo(String value) {
            addCriterion("sub_name >=", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameLessThan(String value) {
            addCriterion("sub_name <", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameLessThanOrEqualTo(String value) {
            addCriterion("sub_name <=", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameLike(String value) {
            addCriterion("sub_name like", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameNotLike(String value) {
            addCriterion("sub_name not like", value, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameIn(List<String> values) {
            addCriterion("sub_name in", values, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameNotIn(List<String> values) {
            addCriterion("sub_name not in", values, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameBetween(String value1, String value2) {
            addCriterion("sub_name between", value1, value2, "subName");
            return (Criteria) this;
        }

        public Criteria andSubNameNotBetween(String value1, String value2) {
            addCriterion("sub_name not between", value1, value2, "subName");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNull() {
            addCriterion("is_pass is null");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNotNull() {
            addCriterion("is_pass is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassEqualTo(Integer value) {
            addCriterion("is_pass =", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotEqualTo(Integer value) {
            addCriterion("is_pass <>", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThan(Integer value) {
            addCriterion("is_pass >", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_pass >=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThan(Integer value) {
            addCriterion("is_pass <", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThanOrEqualTo(Integer value) {
            addCriterion("is_pass <=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassIn(List<Integer> values) {
            addCriterion("is_pass in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotIn(List<Integer> values) {
            addCriterion("is_pass not in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassBetween(Integer value1, Integer value2) {
            addCriterion("is_pass between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotBetween(Integer value1, Integer value2) {
            addCriterion("is_pass not between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andScoreAIsNull() {
            addCriterion("score_a is null");
            return (Criteria) this;
        }

        public Criteria andScoreAIsNotNull() {
            addCriterion("score_a is not null");
            return (Criteria) this;
        }

        public Criteria andScoreAEqualTo(String value) {
            addCriterion("score_a =", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreANotEqualTo(String value) {
            addCriterion("score_a <>", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreAGreaterThan(String value) {
            addCriterion("score_a >", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreAGreaterThanOrEqualTo(String value) {
            addCriterion("score_a >=", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreALessThan(String value) {
            addCriterion("score_a <", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreALessThanOrEqualTo(String value) {
            addCriterion("score_a <=", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreALike(String value) {
            addCriterion("score_a like", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreANotLike(String value) {
            addCriterion("score_a not like", value, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreAIn(List<String> values) {
            addCriterion("score_a in", values, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreANotIn(List<String> values) {
            addCriterion("score_a not in", values, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreABetween(String value1, String value2) {
            addCriterion("score_a between", value1, value2, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreANotBetween(String value1, String value2) {
            addCriterion("score_a not between", value1, value2, "scoreA");
            return (Criteria) this;
        }

        public Criteria andScoreBIsNull() {
            addCriterion("score_b is null");
            return (Criteria) this;
        }

        public Criteria andScoreBIsNotNull() {
            addCriterion("score_b is not null");
            return (Criteria) this;
        }

        public Criteria andScoreBEqualTo(String value) {
            addCriterion("score_b =", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBNotEqualTo(String value) {
            addCriterion("score_b <>", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBGreaterThan(String value) {
            addCriterion("score_b >", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBGreaterThanOrEqualTo(String value) {
            addCriterion("score_b >=", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBLessThan(String value) {
            addCriterion("score_b <", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBLessThanOrEqualTo(String value) {
            addCriterion("score_b <=", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBLike(String value) {
            addCriterion("score_b like", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBNotLike(String value) {
            addCriterion("score_b not like", value, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBIn(List<String> values) {
            addCriterion("score_b in", values, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBNotIn(List<String> values) {
            addCriterion("score_b not in", values, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBBetween(String value1, String value2) {
            addCriterion("score_b between", value1, value2, "scoreB");
            return (Criteria) this;
        }

        public Criteria andScoreBNotBetween(String value1, String value2) {
            addCriterion("score_b not between", value1, value2, "scoreB");
            return (Criteria) this;
        }

        public Criteria andExamTimeIsNull() {
            addCriterion("exam_time is null");
            return (Criteria) this;
        }

        public Criteria andExamTimeIsNotNull() {
            addCriterion("exam_time is not null");
            return (Criteria) this;
        }

        public Criteria andExamTimeEqualTo(Long value) {
            addCriterion("exam_time =", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotEqualTo(Long value) {
            addCriterion("exam_time <>", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeGreaterThan(Long value) {
            addCriterion("exam_time >", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("exam_time >=", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeLessThan(Long value) {
            addCriterion("exam_time <", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeLessThanOrEqualTo(Long value) {
            addCriterion("exam_time <=", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeIn(List<Long> values) {
            addCriterion("exam_time in", values, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotIn(List<Long> values) {
            addCriterion("exam_time not in", values, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeBetween(Long value1, Long value2) {
            addCriterion("exam_time between", value1, value2, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotBetween(Long value1, Long value2) {
            addCriterion("exam_time not between", value1, value2, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamRoomIsNull() {
            addCriterion("exam_room is null");
            return (Criteria) this;
        }

        public Criteria andExamRoomIsNotNull() {
            addCriterion("exam_room is not null");
            return (Criteria) this;
        }

        public Criteria andExamRoomEqualTo(String value) {
            addCriterion("exam_room =", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomNotEqualTo(String value) {
            addCriterion("exam_room <>", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomGreaterThan(String value) {
            addCriterion("exam_room >", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomGreaterThanOrEqualTo(String value) {
            addCriterion("exam_room >=", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomLessThan(String value) {
            addCriterion("exam_room <", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomLessThanOrEqualTo(String value) {
            addCriterion("exam_room <=", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomLike(String value) {
            addCriterion("exam_room like", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomNotLike(String value) {
            addCriterion("exam_room not like", value, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomIn(List<String> values) {
            addCriterion("exam_room in", values, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomNotIn(List<String> values) {
            addCriterion("exam_room not in", values, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomBetween(String value1, String value2) {
            addCriterion("exam_room between", value1, value2, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamRoomNotBetween(String value1, String value2) {
            addCriterion("exam_room not between", value1, value2, "examRoom");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoIsNull() {
            addCriterion("exam_machine_no is null");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoIsNotNull() {
            addCriterion("exam_machine_no is not null");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoEqualTo(String value) {
            addCriterion("exam_machine_no =", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoNotEqualTo(String value) {
            addCriterion("exam_machine_no <>", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoGreaterThan(String value) {
            addCriterion("exam_machine_no >", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoGreaterThanOrEqualTo(String value) {
            addCriterion("exam_machine_no >=", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoLessThan(String value) {
            addCriterion("exam_machine_no <", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoLessThanOrEqualTo(String value) {
            addCriterion("exam_machine_no <=", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoLike(String value) {
            addCriterion("exam_machine_no like", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoNotLike(String value) {
            addCriterion("exam_machine_no not like", value, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoIn(List<String> values) {
            addCriterion("exam_machine_no in", values, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoNotIn(List<String> values) {
            addCriterion("exam_machine_no not in", values, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoBetween(String value1, String value2) {
            addCriterion("exam_machine_no between", value1, value2, "examMachineNo");
            return (Criteria) this;
        }

        public Criteria andExamMachineNoNotBetween(String value1, String value2) {
            addCriterion("exam_machine_no not between", value1, value2, "examMachineNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver_subject
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 21 23:08:34 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driver_subject
     *
     * @mbg.generated Tue Jan 21 23:08:34 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}